title: "Navigation"
description: |
  Navigation buttons are used to access other parts and sections of the page and perform functions like moving to the next and previous page.

patterns:
  buy-now-card:
    title: "Buy now card"
    description: |
      A card that lists a product with its price and a buy now button.
